#!/usr/bin/env python3
"""Minimal orchestrator for the SQANTI-MOD pipeline.

This wrapper lets the user provide the files that are typically generated by the
workflow, and then runs the relevant commands in the same order as the project
scripts:

1. modkit pileup -> produces the filtered BED file from a BAM.
2. saca_tags_transcript_models.py -> turns the BAM/GTF into transcript-level
   modification TSVs.
3. collapse_to_tx_and_merge.py -> merges the TSV output with the SQANTI
   classification file.

The pipeline is intentionally conservative: if some intermediate dependency is
missing (for example the IsoQuant read-to-transcript association file needed by
saca_tags_transcript_models.py), the script skips that stage and prints a clear
warning instead of failing blindly.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_MODS = [
    "m6A"
]


def run(cmd: list[str], *, cwd: Path | None = None) -> None:
    print("\n>>", " ".join(str(x) for x in cmd))
    subprocess.run(cmd, cwd=str(cwd) if cwd else None, check=True)


def build_filtered_bed(
    bam_path: Path,
    reference_path: Path,
    sample: str,
    out_dir: Path,
    modkit_bin: str,
    mods: list[str],
    min_genomic_cov: int,
) -> Path:
    # Creamos el directorio output si no está ya creado
    print("Starting modkit bed generation and filtering")
    bed_dir = out_dir 
    bed_dir.mkdir(parents=True, exist_ok=True)
    cpus = int(os.environ.get('SLURM_CPUS_PER_TASK', 4))
    bed_path = bed_dir / f"{sample}.bed"
    filtered_path = bed_dir / f"{sample}_filtered.bed"
    log_path = out_dir / "logs" / f"pileup_{sample}.txt"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        modkit_bin,
        "pileup",
        str(bam_path),
        str(bed_path),
        "--modified-bases",
        *mods,
        "--reference",
        str(reference_path),
        "--log",
        str(log_path),
        "-t",
        str(cpus)
    ]
    run(cmd)
    #Filtramos al mínimo inputeado
    with bed_path.open("r", encoding="utf-8") as src, filtered_path.open("w", encoding="utf-8") as dst:
        for line in src:
            if line.startswith("#") or not line.strip():
                dst.write(line)
                continue
            cols = line.rstrip("\n").split("\t")
            if len(cols) < 10:
                continue
            try:
                cov = float(cols[9])
            except ValueError:
                continue
            if cov >= min_genomic_cov:
                dst.write(line)
    print("BED generado y filtrado")

    return filtered_path



def run_mods_to_cigar(
    bam_path: Path,
    gtf_path: Path,
    filtered_bed: Path,
    assoc_path: Path,
    sample: Path,
    out_dir:Path,
    prob_lim: float,
    mods: list
) -> Path:
    print("Starting read to transcript projection")
    out_tsv = f"{out_dir}/{sample}.tsv"
    prof_out = f"{out_dir}/{sample}.sacatags.prof"
    cmd = [
        sys.executable,
        "-u",
        #"-m", "cProfile",
        #"-o", str(prof_out),
        str(ROOT / "saca_tags_transcript_models.py"),
        "--bed",
        str(filtered_bed),
        "--bam",
        str(bam_path),
        "--gtf",
        str(gtf_path),
        "--assoc",
        str(assoc_path),
        "--out_tsv",
        str(out_tsv),
        "--prob_lim",
        str(prob_lim),
        "--mods",
        *mods
    ]
    run(cmd)
    print("Tabla con modificaciones por read generada")
    return out_tsv


def run_collapse_to_tx_and_merge(
    tsv_path: Path,
    classification_path: Path,
    out_dir: Path,
    sample: str,
    min_cov: int,
    min_occ: float,
) -> Path:
    print("Starting transcript-level collapse and classification file merge.")
    out_tsv = f"{out_dir}/{sample}_mod_classification.txt"
    prof_out = f"{out_dir}/{sample}.collapse.prof"
    cmd = [
        sys.executable,
        "-m", "cProfile",
        "-o", str(prof_out),
        str(ROOT / "collapse_to_tx_and_merge.py"),
        "--tsv_in",
        str(tsv_path),
        "--sqanti_class",
        str(classification_path),
        "--out_tsv",
        str(out_tsv),
        "--min_cov",
        str(min_cov),
        "--min_occ",
        str(min_occ),
    ]
    run(cmd)
    print("Classsification enriched with isoform-level modification data:", out_tsv)
    return out_tsv


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Runs the SQANTI-MOD stages for a single BAM/GTF/reads_to_isoform.tsv/classification set."
    )
    
    # Archivos de entrada requeridos
    parser.add_argument("--bam", type=Path, required=True, help="Input BAM file to process.")
    parser.add_argument("--gtf", type=Path, required=True, help="GTF file used by the transcript-level stage.")
    parser.add_argument("--classification", type=Path, required=True, help="SQANTI classification file used for the final merge.")
    parser.add_argument("--reference", type=Path, required=True, help="Reference genome FASTA used for modkit pileup.")
    parser.add_argument("--tsv", type=Path, required=True, help="Read_to_transcript TSV/GZ association file.")
    parser.add_argument("--prefix", type=str,required=True,help="Prefix for final output files")
    # Archivos / directorios opcionales
    parser.add_argument("--output-dir", type=Path, default=None, help="Directory for all outputs.")
    parser.add_argument("--modkit", type=str, default="modkit", help="Path to the modkit binary.")
    
    # Parámetros numéricos / listas con defaults establecidos
    parser.add_argument("--mods", nargs="+", default=DEFAULT_MODS, help="Modifications to inspect with modkit.")
    parser.add_argument("--min-genomic-cov", type=int, default=5, help="Minimum genomic coverage kept in the BED.")
    parser.add_argument("--prob-lim", type=float, default=0.95, help="Probability cutoff for modifications.")
    parser.add_argument("--min-tx-cov", type=int, default=20, help="Minimum read coverage for a modification.")
    parser.add_argument("--min-tx-occ", type=float, default=0.2, help="Minimum modification occupancy.")

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    # Validación adicional para garantizar que los ficheros obligatorios existan realmente
    for filepath, name in [
        (args.bam, "BAM"),
        (args.gtf, "GTF"),
        (args.tsv, "TSV"),
        (args.classification, "Classification"),
        (args.reference, "Reference FASTA")
    ]:
        if not filepath.exists():
            raise FileNotFoundError(f"{name} file not found: {filepath}")
        
    if args.output_dir == None:
        args.output_dir = Path(f"output_{args.prefix}")
        
    args.output_dir.mkdir(parents=True, exist_ok=True)
    filtered_bed = build_filtered_bed(
        bam_path=args.bam,
        reference_path=args.reference,
        sample=args.prefix,
        out_dir=args.output_dir,
        modkit_bin=args.modkit,
        mods=args.mods,
        min_genomic_cov=args.min_genomic_cov,
    )
    tsv_dir = run_mods_to_cigar(
        bam_path=args.bam,
        gtf_path=args.gtf,
        filtered_bed=filtered_bed,
        assoc_path=args.tsv,
        sample=args.prefix,
        out_dir=args.output_dir,
        prob_lim=args.prob_lim,
        mods = args.mods
    )
    
    merge_dir = run_collapse_to_tx_and_merge(
        tsv_path=tsv_dir,
        classification_path=args.classification,
        out_dir=args.output_dir,
        sample=args.prefix,
        min_cov=args.min_tx_cov,
        min_occ=args.min_tx_occ,
    )

    print("\nSQANTI-MOD finished successfully.")
    print(f"BED: {filtered_bed}")
    print(f"TSV directory: {tsv_dir}")
    print(f"Merged outputs: {merge_dir}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as exc:
        print(f"[ERROR] Command failed with exit code {exc.returncode}.", file=sys.stderr)
        raise SystemExit(exc.returncode)