#!/usr/bin/env python3
"""Minimal orchestrator for the SQANTI-MOD pipeline.

This wrapper lets the user provide the files that are typically generated by the
workflow, and then runs the relevant commands in the same order as the project
scripts:

1. modkit pileup -> produces the filtered BED file from a BAM.
2. saca_tags_transcript_models.py -> turns the BAM/GTF into transcript-level
   modification TSVs.
3. collapse_to_tx_and_merge.py -> merges the TSV output with the SQANTI
   classification file.

The pipeline is intentionally conservative: if some intermediate dependency is
missing (for example the IsoQuant read-to-transcript association file needed by
saca_tags_transcript_models.py), the script skips that stage and prints a clear
warning instead of failing blindly.
"""

from __future__ import annotations

import argparse
import configparser
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_MODS = [
    "m5C",
    "m6A",
    "2OmeC",
    "pseU",
    "2OmeU",
    "inosine",
    "2OmeA",
]


def _strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def load_config(config_path: str | Path | None) -> dict[str, str]:
    """Reads values from a .ini or shell-style config file.

    Priority is intentionally simple: values are returned as strings, and the
    calling code resolves CLI > config > fallback.
    """
    if config_path is None:
        return {}

    path = Path(config_path)
    if not path.exists():
        return {}

    config: dict[str, str] = {}
    suffix = path.suffix.lower()

    if suffix in {".ini", ".cfg", ".conf"}:
        parser = configparser.ConfigParser()
        parser.optionxform = str
        parser.read(path, encoding="utf-8")
        for section in parser.sections():
            for key, value in parser.items(section):
                config[key.upper()] = value
        for key, value in parser.defaults().items():
            config[key.upper()] = value
        return config

    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[7:]
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip().upper()
            value = _strip_quotes(value.strip())
            config[key] = value
    return config


def find_default_config() -> Path | None:
    candidates = [
        ROOT / "config.ini",
        ROOT / "config.cfg",
        ROOT / "config.conf",
        ROOT / "config.sh",
        Path.cwd() / "config.ini",
        Path.cwd() / "config.cfg",
        Path.cwd() / "config.conf",
        Path.cwd() / "config.sh",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def resolve_value(cli_value, config_value, fallback=None):
    if cli_value is not None:
        return cli_value
    if config_value is not None:
        return config_value
    return fallback


def parse_mods(value):
    if value is None:
        return DEFAULT_MODS
    if isinstance(value, (list, tuple)):
        return list(value)
    if isinstance(value, str):
        value = value.strip()
        if not value:
            return DEFAULT_MODS
        items = [part.strip() for part in value.replace(",", " ").split()]
        return items or DEFAULT_MODS
    return list(value)


def run(cmd: list[str], *, cwd: Path | None = None) -> None:
    print("\n>>", " ".join(str(x) for x in cmd))
    subprocess.run(cmd, cwd=str(cwd) if cwd else None, check=True)


def sample_name_from_bam(bam_path: Path) -> str:
    name = bam_path.name
    if name.endswith(".bam"):
        return name[:-4]
    if name.endswith(".sam"):
        return name[:-4]
    return name


def build_filtered_bed(
    bam_path: Path,
    reference_path: Path,
    out_dir: Path,
    modkit_bin: str,
    mods: list[str],
    min_genomic_cov: int,
) -> Path:
    sample = sample_name_from_bam(bam_path)
    bed_dir = out_dir / "beds"
    bed_dir.mkdir(parents=True, exist_ok=True)

    bed_path = bed_dir / f"{sample}.bed"
    filtered_path = bed_dir / f"{sample}_filtered.bed"
    log_path = out_dir / "logs" / f"pileup_{sample}.txt"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        modkit_bin,
        "pileup",
        str(bam_path),
        str(bed_path),
        "--modified-bases",
        *mods,
        "--reference",
        str(reference_path),
        "--log",
        str(log_path),
    ]
    run(cmd)

    with bed_path.open("r", encoding="utf-8") as src, filtered_path.open("w", encoding="utf-8") as dst:
        for line in src:
            if line.startswith("#") or not line.strip():
                dst.write(line)
                continue
            cols = line.rstrip("\n").split("\t")
            if len(cols) < 10:
                continue
            try:
                cov = float(cols[9])
            except ValueError:
                continue
            if cov >= min_genomic_cov:
                dst.write(line)

    return filtered_path


def prepare_isoquant_tree(sample_name: str, gtf_path: Path, isoquant_dir: Path, assoc_path: Path | None) -> Path:
    sample_dir = isoquant_dir / sample_name / sample_name
    sample_dir.mkdir(parents=True, exist_ok=True)

    target_gtf = sample_dir / f"{sample_name}.extended_annotation.gtf"
    shutil.copy2(gtf_path, target_gtf)

    if assoc_path is not None:
        target_assoc = sample_dir / f"{sample_name}.transcript_model_reads.tsv.gz"
        if assoc_path.suffix == ".gz":
            shutil.copy2(assoc_path, target_assoc)
        else:
            import gzip

            with assoc_path.open("rt", encoding="utf-8") as src, gzip.open(target_assoc, "wt", encoding="utf-8") as dst:
                dst.write(src.read())

    return isoquant_dir


def run_mods_to_cigar(
    bam_path: Path,
    gtf_path: Path,
    filtered_bed: Path,
    isoquant_dir: Path,
    out_dir: Path,
    prob_lim: float,
    read_assoc_path: Path | None = None,
) -> Path:
    sample = sample_name_from_bam(bam_path)
    temp_isoquant = isoquant_dir if isoquant_dir.exists() else isoquant_dir
    if read_assoc_path is not None:
        prepare_isoquant_tree(sample, gtf_path, temp_isoquant, read_assoc_path)
    elif (temp_isoquant / sample / sample / f"{sample}.transcript_model_reads.tsv.gz").exists():
        pass
    else:
        print(
            "[WARN] No read-to-transcript association file is available for the CIGAR step; "
            f"skipping saca_tags_transcript_models.py for {sample}. "
            "Use --isoquant-dir or --read-transcript-association to enable it."
        )
        return out_dir / "tsvs_transcritos"

    bam_root = temp_isoquant / "bam_input"
    bam_root.mkdir(parents=True, exist_ok=True)
    staged_bam = bam_root / bam_path.name
    shutil.copy2(bam_path, staged_bam)

    tsv_out_dir = out_dir / "tsvs_transcritos"
    tsv_out_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable,
        str(ROOT / "saca_tags_transcript_models.py"),
        "--bam_dir",
        str(bam_root),
        "--bam_suffix",
        ".bam",
        "--bed_dir",
        str(filtered_bed.parent),
        "--isoquant_dir",
        str(temp_isoquant),
        "--out_dir",
        str(tsv_out_dir),
        "--prob_lim",
        str(prob_lim),
    ]
    run(cmd)
    return tsv_out_dir


def run_collapse_to_tx_and_merge(
    tsv_path: Path,
    classification_path: Path,
    out_dir: Path,
    min_cov: int,
    min_occ: float,
) -> Path:
    sample = classification_path.name.replace("_classification.txt", "")
    sqanti_root = out_dir / "sqanti"
    sqanti_run = sqanti_root / f"SQANTI3_QC_isoquant_{sample}"
    sqanti_run.mkdir(parents=True, exist_ok=True)

    staged_classification = sqanti_run / classification_path.name
    shutil.copy2(classification_path, staged_classification)

    if tsv_path.is_dir():
        staged_tsv_dir = out_dir / "tsvs_transcritos"
        staged_tsv_dir.mkdir(parents=True, exist_ok=True)
        candidates = list(staged_tsv_dir.glob(f"{sample}_transcripts_modCIGAR.tsv"))
        if not candidates:
            candidates = list(tsv_path.glob(f"{sample}_transcripts_modCIGAR.tsv"))
        if not candidates:
            raise FileNotFoundError(f"No se encontró el TSV para {sample} en {tsv_path}")
        tsv_input = candidates[0]
    else:
        tsv_input = tsv_path

    merge_out_dir = out_dir / "classifications_mod"
    merge_out_dir.mkdir(parents=True, exist_ok=True)

    # The original script expects the TSVs to live in a folder and the
    # SQANTI directory to contain a *classification.txt file under
    # SQANTI3_QC_isoquant_*.
    cmd = [
        sys.executable,
        str(ROOT / "collapse_to_tx_and_merge.py"),
        "--tsv_dir",
        str(tsv_input.parent),
        "--sqanti_dir",
        str(sqanti_root),
        "--out_dir",
        str(merge_out_dir),
        "--min_cov",
        str(min_cov),
        "--min_occ",
        str(min_occ),
    ]
    run(cmd)
    return merge_out_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Runs the SQANTI-MOD stages for a single BAM/GTF/TSV/classification set."
    )
    parser.add_argument("--config", default=None, help="Path to a config file (.ini/.cfg/.conf or shell-style KEY=VALUE).")
    parser.add_argument("--bam", type=Path, default=None, help="Input BAM file to process.")
    parser.add_argument("--gtf", type=Path, default=None, help="GTF file used by the transcript-level stage.")
    parser.add_argument("--tsv", type=Path, default=None, help="Transcript modification TSV produced by the CIGAR step.")
    parser.add_argument(
        "--classification",
        type=Path,
        default=None,
        help="SQANTI classification file used for the final merge.",
    )
    parser.add_argument(
        "--reference",
        type=Path,
        default=None,
        help="Reference genome FASTA used for modkit pileup.",
    )
    parser.add_argument(
        "--modkit",
        default=None,
        help="Path to the modkit binary. If omitted, the config value is used.",
    )
    parser.add_argument(
        "--isoquant-dir",
        type=Path,
        default=None,
        help="Directory that contains the IsoQuant sample tree. Optional, only needed for the CIGAR stage.",
    )
    parser.add_argument(
        "--read-transcript-association",
        type=Path,
        default=None,
        help="Optional transcript_model_reads TSV/GZ file for the CIGAR stage.",
    )
    parser.add_argument("--output-dir", type=Path, default=None, help="Directory for all outputs.")
    parser.add_argument("--mods", nargs="+", default=None, help="Modifications to inspect with modkit.")
    parser.add_argument("--min-genomic-cov", type=int, default=None, help="Minimum genomic coverage kept in the BED.")
    parser.add_argument("--prob-lim", type=float, default=None, help="Probability cutoff for modifications.")
    parser.add_argument("--min-tx-cov", type=int, default=None, help="Minimum transcript coverage used for collapsing.")
    parser.add_argument("--min-tx-occ", type=float, default=None, help="Minimum transcript occupancy used for collapsing.")
    args = parser.parse_args()

    config_path = args.config or find_default_config()
    config = load_config(config_path)
    if config_path:
        print(f"Using config: {config_path}")

    args.bam = resolve_value(args.bam, config.get("BAM") or config.get("BAM_PATH") or config.get("INPUT_BAM"), None)
    args.gtf = resolve_value(args.gtf, config.get("GTF") or config.get("GTF_PATH") or config.get("INPUT_GTF"), None)
    args.tsv = resolve_value(args.tsv, config.get("TSV") or config.get("TSV_PATH") or config.get("INPUT_TSV"), None)
    args.classification = resolve_value(args.classification, config.get("CLASSIFICATION") or config.get("CLASSIFICATION_PATH"), None)
    args.reference = resolve_value(args.reference, config.get("REFERENCE") or config.get("REF_GENOME"), None)
    args.modkit = resolve_value(args.modkit, config.get("MODKIT") or config.get("MODKIT_BIN"), "modkit")
    args.isoquant_dir = resolve_value(args.isoquant_dir, config.get("ISOQUANT_DIR"), ROOT / "tmp_isoquant")
    args.read_transcript_association = resolve_value(args.read_transcript_association, config.get("READ_TRANSCRIPT_ASSOCIATION") or config.get("TRANSCRIPT_MODEL_READS"), None)
    args.output_dir = resolve_value(args.output_dir, config.get("OUTPUT_DIR"), ROOT / "output")
    args.mods = parse_mods(resolve_value(args.mods, config.get("MODS"), DEFAULT_MODS))
    args.min_genomic_cov = resolve_value(args.min_genomic_cov, config.get("MIN_GENOMIC_COV"), 5)
    args.prob_lim = resolve_value(args.prob_lim, config.get("PROB_LIM"), 0.95)
    args.min_tx_cov = resolve_value(args.min_tx_cov, config.get("MIN_TX_COV"), 20)
    args.min_tx_occ = resolve_value(args.min_tx_occ, config.get("MIN_TX_OCC"), 0.2)

    if args.min_genomic_cov is not None and not isinstance(args.min_genomic_cov, int):
        args.min_genomic_cov = int(args.min_genomic_cov)
    if args.min_tx_cov is not None and not isinstance(args.min_tx_cov, int):
        args.min_tx_cov = int(args.min_tx_cov)
    if args.prob_lim is not None and not isinstance(args.prob_lim, float):
        args.prob_lim = float(args.prob_lim)
    if args.min_tx_occ is not None and not isinstance(args.min_tx_occ, float):
        args.min_tx_occ = float(args.min_tx_occ)

    for field in ["bam", "gtf", "tsv", "classification", "reference", "isoquant_dir", "read_transcript_association", "output_dir"]:
        value = getattr(args, field)
        if value is not None:
            setattr(args, field, Path(value))

    return args


def main() -> int:
    args = parse_args()

    if args.bam is None or not Path(args.bam).exists():
        raise FileNotFoundError(f"BAM file not found: {args.bam}")
    if args.gtf is None or not Path(args.gtf).exists():
        raise FileNotFoundError(f"GTF file not found: {args.gtf}")
    if args.tsv is None or not Path(args.tsv).exists():
        raise FileNotFoundError(f"TSV file not found: {args.tsv}")
    if args.classification is None or not Path(args.classification).exists():
        raise FileNotFoundError(f"Classification file not found: {args.classification}")
    if args.reference is None or not Path(args.reference).exists():
        raise FileNotFoundError(f"Reference FASTA not found: {args.reference}")

    args.output_dir = Path(args.output_dir)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    filtered_bed = build_filtered_bed(
        bam_path=args.bam,
        reference_path=args.reference,
        out_dir=args.output_dir,
        modkit_bin=args.modkit,
        mods=args.mods,
        min_genomic_cov=args.min_genomic_cov,
    )

    tsv_dir = run_mods_to_cigar(
        bam_path=args.bam,
        gtf_path=args.gtf,
        filtered_bed=filtered_bed,
        isoquant_dir=args.isoquant_dir,
        out_dir=args.output_dir,
        prob_lim=args.prob_lim,
        read_assoc_path=args.read_transcript_association,
    )

    # If the user gives an already-built TSV, we can use it directly instead of
    # the output created by the previous step.
    tsv_input = args.tsv if args.tsv.exists() else (tsv_dir / args.tsv.name)
    merge_dir = run_collapse_to_tx_and_merge(
        tsv_path=tsv_input,
        classification_path=args.classification,
        out_dir=args.output_dir,
        min_cov=args.min_tx_cov,
        min_occ=args.min_tx_occ,
    )

    print("\nSQANTI-MOD finished successfully.")
    print(f"BED: {filtered_bed}")
    print(f"TSV directory: {tsv_dir}")
    print(f"Merged outputs: {merge_dir}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as exc:
        print(f"[ERROR] Command failed with exit code {exc.returncode}.", file=sys.stderr)
        raise SystemExit(exc.returncode)
